name: Add Old Meteor Client Versions

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to download old version from (Internet Archive)'
        required: true
      version:
        description: 'Version number of this file'
        required: true
      date:
        description: 'Original release date (YYYY-MM-DD)'
        required: true

permissions:
  contents: write

jobs:
  add-old-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create meteor-client directory if it doesn't exist
        run: mkdir -p meteor-client

      - name: Download old version
        working-directory: meteor-client
        run: |
          curl -L -o "meteor-client-${{ github.event.inputs.version }}.jar" "${{ github.event.inputs.url }}"

      - name: Calculate MD5 hash
        id: hash
        working-directory: meteor-client
        run: |
          md5sum "meteor-client-${{ github.event.inputs.version }}.jar" | awk '{print $1}' > md5.txt
          echo "md5=$(cat md5.txt)" >> $GITHUB_OUTPUT

      - name: Create or update README with table
        run: |
          if [ ! -f README.md ]; then
            # Create new README with table header
            echo "# Meteor Client Archive" > README.md
            echo "" >> README.md
            echo "Automatically updated archive of Meteor Client releases." >> README.md
            echo "" >> README.md
            echo "## Versions" >> README.md
            echo "" >> README.md
            echo "| Date | Filename | Version | MD5 Hash |" >> README.md
            echo "|------|----------|---------|----------|" >> README.md
          fi
          
          # Check if table exists, if not create it
          if ! grep -q "| Date | Filename | Version | MD5 Hash |" README.md; then
            echo "" >> README.md
            echo "## Versions" >> README.md
            echo "" >> README.md
            echo "| Date | Filename | Version | MD5 Hash |" >> README.md
            echo "|------|----------|---------|----------|" >> README.md
          fi
          
          # Add new row to table (at the bottom)
          echo "| ${{ github.event.inputs.date }} | [meteor-client-${{ github.event.inputs.version }}.jar](meteor-client/meteor-client-${{ github.event.inputs.version }}.jar) | ${{ github.event.inputs.version }} | \`${{ steps.hash.outputs.md5 }}\` |" >> README.md
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add meteor-client/"meteor-client-${{ github.event.inputs.version }}.jar" README.md
          git commit -m "Add old Meteor Client version ${{ github.event.inputs.version }} from archive"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
